mock_data = {u'count': 87,
 u'next': u'http://www.swapi.co/api/people/?page=2',
 u'previous': None,
 u'results': [{u'birth_year': u'19BBY',
   u'created': u'2014-12-09T13:50:51.644000Z',
   u'edited': u'2014-12-20T21:17:56.891000Z',
   u'eye_color': u'blue',
   u'films': [u'http://www.swapi.co/api/films/6/',
    u'http://www.swapi.co/api/films/3/',
    u'http://www.swapi.co/api/films/2/',
    u'http://www.swapi.co/api/films/1/',
    u'http://www.swapi.co/api/films/7/'],
   u'gender': u'male',
   u'hair_color': u'blond',
   u'height': u'172',
   u'homeworld': u'http://www.swapi.co/api/planets/1/',
   u'mass': u'77',
   u'name': u'Luke Skywalker',
   u'skin_color': u'fair',
   u'species': [u'http://www.swapi.co/api/species/1/'],
   u'starships': [u'http://www.swapi.co/api/starships/12/',
    u'http://www.swapi.co/api/starships/22/'],
   u'url': u'http://www.swapi.co/api/people/1/',
   u'vehicles': [u'http://www.swapi.co/api/vehicles/14/',
    u'http://www.swapi.co/api/vehicles/30/']},
  {u'birth_year': u'112BBY',
   u'created': u'2014-12-10T15:10:51.357000Z',
   u'edited': u'2014-12-20T21:17:50.309000Z',
   u'eye_color': u'yellow',
   u'films': [u'http://www.swapi.co/api/films/5/',
    u'http://www.swapi.co/api/films/4/',
    u'http://www.swapi.co/api/films/6/',
    u'http://www.swapi.co/api/films/3/',
    u'http://www.swapi.co/api/films/2/',
    u'http://www.swapi.co/api/films/1/'],
   u'gender': u'n/a',
   u'hair_color': u'n/a',
   u'height': u'167',
   u'homeworld': u'http://www.swapi.co/api/planets/1/',
   u'mass': u'75',
   u'name': u'C-3PO',
   u'skin_color': u'gold',
   u'species': [u'http://www.swapi.co/api/species/2/'],
   u'starships': [],
   u'url': u'http://www.swapi.co/api/people/2/',
   u'vehicles': []},
  {u'birth_year': u'33BBY',
   u'created': u'2014-12-10T15:11:50.376000Z',
   u'edited': u'2014-12-20T21:17:50.311000Z',
   u'eye_color': u'red',
   u'films': [u'http://www.swapi.co/api/films/5/',
    u'http://www.swapi.co/api/films/4/',
    u'http://www.swapi.co/api/films/6/',
    u'http://www.swapi.co/api/films/3/',
    u'http://www.swapi.co/api/films/2/',
    u'http://www.swapi.co/api/films/1/',
    u'http://www.swapi.co/api/films/7/'],
   u'gender': u'n/a',
   u'hair_color': u'n/a',
   u'height': u'96',
   u'homeworld': u'http://www.swapi.co/api/planets/8/',
   u'mass': u'32',
   u'name': u'R2-D2',
   u'skin_color': u'white, blue',
   u'species': [u'http://www.swapi.co/api/species/2/'],
   u'starships': [],
   u'url': u'http://www.swapi.co/api/people/3/',
   u'vehicles': []},
  {u'birth_year': u'41.9BBY',
   u'created': u'2014-12-10T15:18:20.704000Z',
   u'edited': u'2014-12-20T21:17:50.313000Z',
   u'eye_color': u'yellow',
   u'films': [u'http://www.swapi.co/api/films/6/',
    u'http://www.swapi.co/api/films/3/',
    u'http://www.swapi.co/api/films/2/',
    u'http://www.swapi.co/api/films/1/'],
   u'gender': u'male',
   u'hair_color': u'none',
   u'height': u'202',
   u'homeworld': u'http://www.swapi.co/api/planets/1/',
   u'mass': u'136',
   u'name': u'Darth Vader',
   u'skin_color': u'white',
   u'species': [u'http://www.swapi.co/api/species/1/'],
   u'starships': [u'http://www.swapi.co/api/starships/13/'],
   u'url': u'http://www.swapi.co/api/people/4/',
   u'vehicles': []},
  {u'birth_year': u'19BBY',
   u'created': u'2014-12-10T15:20:09.791000Z',
   u'edited': u'2014-12-20T21:17:50.315000Z',
   u'eye_color': u'brown',
   u'films': [u'http://www.swapi.co/api/films/6/',
    u'http://www.swapi.co/api/films/3/',
    u'http://www.swapi.co/api/films/2/',
    u'http://www.swapi.co/api/films/1/',
    u'http://www.swapi.co/api/films/7/'],
   u'gender': u'female',
   u'hair_color': u'brown',
   u'height': u'150',
   u'homeworld': u'http://www.swapi.co/api/planets/2/',
   u'mass': u'49',
   u'name': u'Leia Organa',
   u'skin_color': u'light',
   u'species': [u'http://www.swapi.co/api/species/1/'],
   u'starships': [],
   u'url': u'http://www.swapi.co/api/people/5/',
   u'vehicles': [u'http://www.swapi.co/api/vehicles/30/']},
  {u'birth_year': u'52BBY',
   u'created': u'2014-12-10T15:52:14.024000Z',
   u'edited': u'2014-12-20T21:17:50.317000Z',
   u'eye_color': u'blue',
   u'films': [u'http://www.swapi.co/api/films/5/',
    u'http://www.swapi.co/api/films/6/',
    u'http://www.swapi.co/api/films/1/'],
   u'gender': u'male',
   u'hair_color': u'brown, grey',
   u'height': u'178',
   u'homeworld': u'http://www.swapi.co/api/planets/1/',
   u'mass': u'120',
   u'name': u'Owen Lars',
   u'skin_color': u'light',
   u'species': [u'http://www.swapi.co/api/species/1/'],
   u'starships': [],
   u'url': u'http://www.swapi.co/api/people/6/',
   u'vehicles': []},
  {u'birth_year': u'47BBY',
   u'created': u'2014-12-10T15:53:41.121000Z',
   u'edited': u'2014-12-20T21:17:50.319000Z',
   u'eye_color': u'blue',
   u'films': [u'http://www.swapi.co/api/films/5/',
    u'http://www.swapi.co/api/films/6/',
    u'http://www.swapi.co/api/films/1/'],
   u'gender': u'female',
   u'hair_color': u'brown',
   u'height': u'165',
   u'homeworld': u'http://www.swapi.co/api/planets/1/',
   u'mass': u'75',
   u'name': u'Beru Whitesun lars',
   u'skin_color': u'light',
   u'species': [u'http://www.swapi.co/api/species/1/'],
   u'starships': [],
   u'url': u'http://www.swapi.co/api/people/7/',
   u'vehicles': []},
  {u'birth_year': u'unknown',
   u'created': u'2014-12-10T15:57:50.959000Z',
   u'edited': u'2014-12-20T21:17:50.321000Z',
   u'eye_color': u'red',
   u'films': [u'http://www.swapi.co/api/films/1/'],
   u'gender': u'n/a',
   u'hair_color': u'n/a',
   u'height': u'97',
   u'homeworld': u'http://www.swapi.co/api/planets/1/',
   u'mass': u'32',
   u'name': u'R5-D4',
   u'skin_color': u'white, red',
   u'species': [u'http://www.swapi.co/api/species/2/'],
   u'starships': [],
   u'url': u'http://www.swapi.co/api/people/8/',
   u'vehicles': []},
  {u'birth_year': u'24BBY',
   u'created': u'2014-12-10T15:59:50.509000Z',
   u'edited': u'2014-12-20T21:17:50.323000Z',
   u'eye_color': u'brown',
   u'films': [u'http://www.swapi.co/api/films/1/'],
   u'gender': u'male',
   u'hair_color': u'black',
   u'height': u'183',
   u'homeworld': u'http://www.swapi.co/api/planets/1/',
   u'mass': u'84',
   u'name': u'Biggs Darklighter',
   u'skin_color': u'light',
   u'species': [u'http://www.swapi.co/api/species/1/'],
   u'starships': [u'http://www.swapi.co/api/starships/12/'],
   u'url': u'http://www.swapi.co/api/people/9/',
   u'vehicles': []},
  {u'birth_year': u'57BBY',
   u'created': u'2014-12-10T16:16:29.192000Z',
   u'edited': u'2014-12-20T21:17:50.325000Z',
   u'eye_color': u'blue-gray',
   u'films': [u'http://www.swapi.co/api/films/5/',
    u'http://www.swapi.co/api/films/4/',
    u'http://www.swapi.co/api/films/6/',
    u'http://www.swapi.co/api/films/3/',
    u'http://www.swapi.co/api/films/2/',
    u'http://www.swapi.co/api/films/1/'],
   u'gender': u'male',
   u'hair_color': u'auburn, white',
   u'height': u'182',
   u'homeworld': u'http://www.swapi.co/api/planets/20/',
   u'mass': u'77',
   u'name': u'Obi-Wan Kenobi',
   u'skin_color': u'fair',
   u'species': [u'http://www.swapi.co/api/species/1/'],
   u'starships': [u'http://www.swapi.co/api/starships/48/',
    u'http://www.swapi.co/api/starships/59/',
    u'http://www.swapi.co/api/starships/64/',
    u'http://www.swapi.co/api/starships/65/',
    u'http://www.swapi.co/api/starships/74/'],
   u'url': u'http://www.swapi.co/api/people/10/',
   u'vehicles': [u'http://www.swapi.co/api/vehicles/38/']}]}